package cn.wsn331.om.model;

import java.util.Date;

public class AirQuality extends Entity {
    private static final long serialVersionUID = 7108466889068283759L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_air_quality.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_air_quality.C_PM25
     *
     * @mbggenerated
     */
    private Float pm25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_air_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_air_quality.C_ID
     *
     * @return the value of d_air_quality.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_air_quality.C_ID
     *
     * @param id the value for d_air_quality.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_air_quality.C_PM25
     *
     * @return the value of d_air_quality.C_PM25
     *
     * @mbggenerated
     */
    public Float getPm25() {
        return pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_air_quality.C_PM25
     *
     * @param pm25 the value for d_air_quality.C_PM25
     *
     * @mbggenerated
     */
    public void setPm25(Float pm25) {
        this.pm25 = pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_air_quality.C_CREATE_TIME
     *
     * @return the value of d_air_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_air_quality.C_CREATE_TIME
     *
     * @param createTime the value for d_air_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}