package cn.wsn331.om.model;

import java.util.Date;

public class AirQuality extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_air_quality.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_air_quality.C_PM25
     *
     * @mbggenerated
     */
    private Float pm25;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_air_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_air_quality.C_USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_air_quality.C_DEVICE_ID
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_air_quality.C_ID
     *
     * @return the value of d_air_quality.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_air_quality.C_ID
     *
     * @param id the value for d_air_quality.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_air_quality.C_PM25
     *
     * @return the value of d_air_quality.C_PM25
     *
     * @mbggenerated
     */
    public Float getPm25() {
        return pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_air_quality.C_PM25
     *
     * @param pm25 the value for d_air_quality.C_PM25
     *
     * @mbggenerated
     */
    public void setPm25(Float pm25) {
        this.pm25 = pm25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_air_quality.C_CREATE_TIME
     *
     * @return the value of d_air_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_air_quality.C_CREATE_TIME
     *
     * @param createTime the value for d_air_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_air_quality.C_USER_ID
     *
     * @return the value of d_air_quality.C_USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_air_quality.C_USER_ID
     *
     * @param userId the value for d_air_quality.C_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_air_quality.C_DEVICE_ID
     *
     * @return the value of d_air_quality.C_DEVICE_ID
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_air_quality.C_DEVICE_ID
     *
     * @param deviceId the value for d_air_quality.C_DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_air_quality
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", pm25=").append(pm25);
        sb.append(", createTime=").append(createTime);
        sb.append(", userId=").append(userId);
        sb.append(", deviceId=").append(deviceId);
        sb.append("]");
        return sb.toString();
    }
}