package cn.wsn331.om.model;

public class DeviceAttr extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr.C_CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr.C_NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_device_attr.C_DEVICE_ID
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr.C_ID
     *
     * @return the value of t_device_attr.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr.C_ID
     *
     * @param id the value for t_device_attr.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr.C_CODE
     *
     * @return the value of t_device_attr.C_CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr.C_CODE
     *
     * @param code the value for t_device_attr.C_CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr.C_NAME
     *
     * @return the value of t_device_attr.C_NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr.C_NAME
     *
     * @param name the value for t_device_attr.C_NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_device_attr.C_DEVICE_ID
     *
     * @return the value of t_device_attr.C_DEVICE_ID
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_device_attr.C_DEVICE_ID
     *
     * @param deviceId the value for t_device_attr.C_DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device_attr
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", code=").append(code);
        sb.append(", name=").append(name);
        sb.append(", deviceId=").append(deviceId);
        sb.append("]");
        return sb.toString();
    }
}