package cn.wsn331.om.model;

import java.util.Date;

public class Formaldehyde extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_formaldehyde.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_formaldehyde.C_FORMALDEHYDE
     *
     * @mbggenerated
     */
    private Float formaldehyde;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_formaldehyde.C_INDOOR_TEMPERATURE
     *
     * @mbggenerated
     */
    private Float indoorTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_formaldehyde.C_OUTDOOR_TEMPERATURE
     *
     * @mbggenerated
     */
    private Float outdoorTemperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_formaldehyde.C_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_formaldehyde.C_USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_formaldehyde.C_DEVICE_ID
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_formaldehyde.C_ID
     *
     * @return the value of d_formaldehyde.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_formaldehyde.C_ID
     *
     * @param id the value for d_formaldehyde.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_formaldehyde.C_FORMALDEHYDE
     *
     * @return the value of d_formaldehyde.C_FORMALDEHYDE
     *
     * @mbggenerated
     */
    public Float getFormaldehyde() {
        return formaldehyde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_formaldehyde.C_FORMALDEHYDE
     *
     * @param formaldehyde the value for d_formaldehyde.C_FORMALDEHYDE
     *
     * @mbggenerated
     */
    public void setFormaldehyde(Float formaldehyde) {
        this.formaldehyde = formaldehyde;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_formaldehyde.C_INDOOR_TEMPERATURE
     *
     * @return the value of d_formaldehyde.C_INDOOR_TEMPERATURE
     *
     * @mbggenerated
     */
    public Float getIndoorTemperature() {
        return indoorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_formaldehyde.C_INDOOR_TEMPERATURE
     *
     * @param indoorTemperature the value for d_formaldehyde.C_INDOOR_TEMPERATURE
     *
     * @mbggenerated
     */
    public void setIndoorTemperature(Float indoorTemperature) {
        this.indoorTemperature = indoorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_formaldehyde.C_OUTDOOR_TEMPERATURE
     *
     * @return the value of d_formaldehyde.C_OUTDOOR_TEMPERATURE
     *
     * @mbggenerated
     */
    public Float getOutdoorTemperature() {
        return outdoorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_formaldehyde.C_OUTDOOR_TEMPERATURE
     *
     * @param outdoorTemperature the value for d_formaldehyde.C_OUTDOOR_TEMPERATURE
     *
     * @mbggenerated
     */
    public void setOutdoorTemperature(Float outdoorTemperature) {
        this.outdoorTemperature = outdoorTemperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_formaldehyde.C_CREATE_TIME
     *
     * @return the value of d_formaldehyde.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_formaldehyde.C_CREATE_TIME
     *
     * @param createTime the value for d_formaldehyde.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_formaldehyde.C_USER_ID
     *
     * @return the value of d_formaldehyde.C_USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_formaldehyde.C_USER_ID
     *
     * @param userId the value for d_formaldehyde.C_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_formaldehyde.C_DEVICE_ID
     *
     * @return the value of d_formaldehyde.C_DEVICE_ID
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_formaldehyde.C_DEVICE_ID
     *
     * @param deviceId the value for d_formaldehyde.C_DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_formaldehyde
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", formaldehyde=").append(formaldehyde);
        sb.append(", indoorTemperature=").append(indoorTemperature);
        sb.append(", outdoorTemperature=").append(outdoorTemperature);
        sb.append(", createTime=").append(createTime);
        sb.append(", userId=").append(userId);
        sb.append(", deviceId=").append(deviceId);
        sb.append("]");
        return sb.toString();
    }
}