package cn.wsn331.om.model;

import java.util.Date;

public class Frame extends Entity {
    private static final long serialVersionUID = 6238993354560198780L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_frame.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_frame.C_ELECTRIC_QUANTITY
     *
     * @mbggenerated
     */
    private Float electricQuantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_frame.C_VOLTAGE
     *
     * @mbggenerated
     */
    private Float voltage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_frame.C_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_frame.C_ID
     *
     * @return the value of d_frame.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_frame.C_ID
     *
     * @param id the value for d_frame.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_frame.C_ELECTRIC_QUANTITY
     *
     * @return the value of d_frame.C_ELECTRIC_QUANTITY
     *
     * @mbggenerated
     */
    public Float getElectricQuantity() {
        return electricQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_frame.C_ELECTRIC_QUANTITY
     *
     * @param electricQuantity the value for d_frame.C_ELECTRIC_QUANTITY
     *
     * @mbggenerated
     */
    public void setElectricQuantity(Float electricQuantity) {
        this.electricQuantity = electricQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_frame.C_VOLTAGE
     *
     * @return the value of d_frame.C_VOLTAGE
     *
     * @mbggenerated
     */
    public Float getVoltage() {
        return voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_frame.C_VOLTAGE
     *
     * @param voltage the value for d_frame.C_VOLTAGE
     *
     * @mbggenerated
     */
    public void setVoltage(Float voltage) {
        this.voltage = voltage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_frame.C_CREATE_TIME
     *
     * @return the value of d_frame.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_frame.C_CREATE_TIME
     *
     * @param createTime the value for d_frame.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}