package cn.wsn331.om.model;

import java.util.Date;

public class ShoppingCar extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_car.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_car.C_TRADE_ID
     *
     * @mbggenerated
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_car.C_USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_car.C_PRICE
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_car.C_COUNT
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_car.C_SUM_PRICE
     *
     * @mbggenerated
     */
    private Float sumPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_shopping_car.C_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_car.C_ID
     *
     * @return the value of t_shopping_car.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_car.C_ID
     *
     * @param id the value for t_shopping_car.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_car.C_TRADE_ID
     *
     * @return the value of t_shopping_car.C_TRADE_ID
     *
     * @mbggenerated
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_car.C_TRADE_ID
     *
     * @param tradeId the value for t_shopping_car.C_TRADE_ID
     *
     * @mbggenerated
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_car.C_USER_ID
     *
     * @return the value of t_shopping_car.C_USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_car.C_USER_ID
     *
     * @param userId the value for t_shopping_car.C_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_car.C_PRICE
     *
     * @return the value of t_shopping_car.C_PRICE
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_car.C_PRICE
     *
     * @param price the value for t_shopping_car.C_PRICE
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_car.C_COUNT
     *
     * @return the value of t_shopping_car.C_COUNT
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_car.C_COUNT
     *
     * @param count the value for t_shopping_car.C_COUNT
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_car.C_SUM_PRICE
     *
     * @return the value of t_shopping_car.C_SUM_PRICE
     *
     * @mbggenerated
     */
    public Float getSumPrice() {
        return sumPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_car.C_SUM_PRICE
     *
     * @param sumPrice the value for t_shopping_car.C_SUM_PRICE
     *
     * @mbggenerated
     */
    public void setSumPrice(Float sumPrice) {
        this.sumPrice = sumPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_shopping_car.C_CREATE_TIME
     *
     * @return the value of t_shopping_car.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_shopping_car.C_CREATE_TIME
     *
     * @param createTime the value for t_shopping_car.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_car
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tradeId=").append(tradeId);
        sb.append(", userId=").append(userId);
        sb.append(", price=").append(price);
        sb.append(", count=").append(count);
        sb.append(", sumPrice=").append(sumPrice);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}