package cn.wsn331.om.model;

public class TradeOrderSingle extends Entity {
    private static final long serialVersionUID = 841383239628957432L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_order_single.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_order_single.C_TRADE_ORDER_ID
     *
     * @mbggenerated
     */
    private String tradeOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_order_single.C_TRADE_ID
     *
     * @mbggenerated
     */
    private Integer tradeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_order_single.C_USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_order_single.C_PRICE
     *
     * @mbggenerated
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_order_single.C_COUNT
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_order_single.C_SUM_PRICE
     *
     * @mbggenerated
     */
    private Float sumPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_order_single.C_ID
     *
     * @return the value of t_trade_order_single.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_order_single.C_ID
     *
     * @param id the value for t_trade_order_single.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_order_single.C_TRADE_ORDER_ID
     *
     * @return the value of t_trade_order_single.C_TRADE_ORDER_ID
     *
     * @mbggenerated
     */
    public String getTradeOrderId() {
        return tradeOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_order_single.C_TRADE_ORDER_ID
     *
     * @param tradeOrderId the value for t_trade_order_single.C_TRADE_ORDER_ID
     *
     * @mbggenerated
     */
    public void setTradeOrderId(String tradeOrderId) {
        this.tradeOrderId = tradeOrderId == null ? null : tradeOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_order_single.C_TRADE_ID
     *
     * @return the value of t_trade_order_single.C_TRADE_ID
     *
     * @mbggenerated
     */
    public Integer getTradeId() {
        return tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_order_single.C_TRADE_ID
     *
     * @param tradeId the value for t_trade_order_single.C_TRADE_ID
     *
     * @mbggenerated
     */
    public void setTradeId(Integer tradeId) {
        this.tradeId = tradeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_order_single.C_USER_ID
     *
     * @return the value of t_trade_order_single.C_USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_order_single.C_USER_ID
     *
     * @param userId the value for t_trade_order_single.C_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_order_single.C_PRICE
     *
     * @return the value of t_trade_order_single.C_PRICE
     *
     * @mbggenerated
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_order_single.C_PRICE
     *
     * @param price the value for t_trade_order_single.C_PRICE
     *
     * @mbggenerated
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_order_single.C_COUNT
     *
     * @return the value of t_trade_order_single.C_COUNT
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_order_single.C_COUNT
     *
     * @param count the value for t_trade_order_single.C_COUNT
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_trade_order_single.C_SUM_PRICE
     *
     * @return the value of t_trade_order_single.C_SUM_PRICE
     *
     * @mbggenerated
     */
    public Float getSumPrice() {
        return sumPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_order_single.C_SUM_PRICE
     *
     * @param sumPrice the value for t_trade_order_single.C_SUM_PRICE
     *
     * @mbggenerated
     */
    public void setSumPrice(Float sumPrice) {
        this.sumPrice = sumPrice;
    }
}