package cn.wsn331.om.model;

import java.util.Date;

public class UDisk extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_SPACE
     *
     * @mbggenerated
     */
    private Float space;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_USED_SPACE
     *
     * @mbggenerated
     */
    private Float usedSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_USER_ID
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_DEVICE_ID
     *
     * @mbggenerated
     */
    private Integer deviceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_ID
     *
     * @return the value of d_u_disk.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_ID
     *
     * @param id the value for d_u_disk.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_SPACE
     *
     * @return the value of d_u_disk.C_SPACE
     *
     * @mbggenerated
     */
    public Float getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_SPACE
     *
     * @param space the value for d_u_disk.C_SPACE
     *
     * @mbggenerated
     */
    public void setSpace(Float space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_USED_SPACE
     *
     * @return the value of d_u_disk.C_USED_SPACE
     *
     * @mbggenerated
     */
    public Float getUsedSpace() {
        return usedSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_USED_SPACE
     *
     * @param usedSpace the value for d_u_disk.C_USED_SPACE
     *
     * @mbggenerated
     */
    public void setUsedSpace(Float usedSpace) {
        this.usedSpace = usedSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_CREATE_TIME
     *
     * @return the value of d_u_disk.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_CREATE_TIME
     *
     * @param createTime the value for d_u_disk.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_USER_ID
     *
     * @return the value of d_u_disk.C_USER_ID
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_USER_ID
     *
     * @param userId the value for d_u_disk.C_USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_DEVICE_ID
     *
     * @return the value of d_u_disk.C_DEVICE_ID
     *
     * @mbggenerated
     */
    public Integer getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_DEVICE_ID
     *
     * @param deviceId the value for d_u_disk.C_DEVICE_ID
     *
     * @mbggenerated
     */
    public void setDeviceId(Integer deviceId) {
        this.deviceId = deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_u_disk
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", space=").append(space);
        sb.append(", usedSpace=").append(usedSpace);
        sb.append(", createTime=").append(createTime);
        sb.append(", userId=").append(userId);
        sb.append(", deviceId=").append(deviceId);
        sb.append("]");
        return sb.toString();
    }
}