package cn.wsn331.om.model;

import java.util.Date;

public class UDisk extends Entity {
    private static final long serialVersionUID = 1677496348980299031L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_SPACE
     *
     * @mbggenerated
     */
    private Float space;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_USED_SPACE
     *
     * @mbggenerated
     */
    private Float usedSpace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_u_disk.C_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_ID
     *
     * @return the value of d_u_disk.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_ID
     *
     * @param id the value for d_u_disk.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_SPACE
     *
     * @return the value of d_u_disk.C_SPACE
     *
     * @mbggenerated
     */
    public Float getSpace() {
        return space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_SPACE
     *
     * @param space the value for d_u_disk.C_SPACE
     *
     * @mbggenerated
     */
    public void setSpace(Float space) {
        this.space = space;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_USED_SPACE
     *
     * @return the value of d_u_disk.C_USED_SPACE
     *
     * @mbggenerated
     */
    public Float getUsedSpace() {
        return usedSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_USED_SPACE
     *
     * @param usedSpace the value for d_u_disk.C_USED_SPACE
     *
     * @mbggenerated
     */
    public void setUsedSpace(Float usedSpace) {
        this.usedSpace = usedSpace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_u_disk.C_CREATE_TIME
     *
     * @return the value of d_u_disk.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_u_disk.C_CREATE_TIME
     *
     * @param createTime the value for d_u_disk.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}