package cn.wsn331.om.model;

import java.util.Date;

public class WaterQuality extends Entity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_water_quality.C_ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_water_quality.C_TDS
     *
     * @mbggenerated
     */
    private Float tds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_water_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_water_quality.C_ID
     *
     * @return the value of d_water_quality.C_ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_water_quality.C_ID
     *
     * @param id the value for d_water_quality.C_ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_water_quality.C_TDS
     *
     * @return the value of d_water_quality.C_TDS
     *
     * @mbggenerated
     */
    public Float getTds() {
        return tds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_water_quality.C_TDS
     *
     * @param tds the value for d_water_quality.C_TDS
     *
     * @mbggenerated
     */
    public void setTds(Float tds) {
        this.tds = tds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_water_quality.C_CREATE_TIME
     *
     * @return the value of d_water_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_water_quality.C_CREATE_TIME
     *
     * @param createTime the value for d_water_quality.C_CREATE_TIME
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_water_quality
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tds=").append(tds);
        sb.append(", createTime=").append(createTime);
        sb.append("]");
        return sb.toString();
    }
}