package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.AirQuality;
import shit.ssm1.mybatis.BaseMapper;

public interface AirQualityMapper extends BaseMapper<AirQuality, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_air_quality
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_air_quality
     *
     * @mbggenerated
     */
    int insert(AirQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_air_quality
     *
     * @mbggenerated
     */
    int insertSelective(AirQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_air_quality
     *
     * @mbggenerated
     */
    AirQuality selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_air_quality
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AirQuality record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_air_quality
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AirQuality record);
}