package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.Device;
import shit.ssm1.mybatis.BaseMapper;

public interface DeviceMapper extends BaseMapper<Device, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int insert(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int insertSelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    Device selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Device record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_device
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Device record);
}