package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.Formaldehyde;
import shit.ssm1.mybatis.BaseMapper;

public interface FormaldehydeMapper extends BaseMapper<Formaldehyde, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_formaldehyde
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_formaldehyde
     *
     * @mbggenerated
     */
    int insert(Formaldehyde record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_formaldehyde
     *
     * @mbggenerated
     */
    int insertSelective(Formaldehyde record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_formaldehyde
     *
     * @mbggenerated
     */
    Formaldehyde selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_formaldehyde
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Formaldehyde record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_formaldehyde
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Formaldehyde record);
}