package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.Frame;
import shit.ssm1.mybatis.BaseMapper;

public interface FrameMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_frame
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_frame
     *
     * @mbggenerated
     */
    int insert(Frame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_frame
     *
     * @mbggenerated
     */
    int insertSelective(Frame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_frame
     *
     * @mbggenerated
     */
    Frame selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_frame
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Frame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_frame
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Frame record);
}