package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.ShoppingCar;
import shit.ssm1.mybatis.BaseMapper;

public interface ShoppingCarMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_car
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_car
     *
     * @mbggenerated
     */
    int insert(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_car
     *
     * @mbggenerated
     */
    int insertSelective(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_car
     *
     * @mbggenerated
     */
    ShoppingCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ShoppingCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_shopping_car
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ShoppingCar record);
}