package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.TradeOrder;
import shit.ssm1.mybatis.BaseMapper;

public interface TradeOrderMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_order
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_order
     *
     * @mbggenerated
     */
    int insert(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_order
     *
     * @mbggenerated
     */
    int insertSelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_order
     *
     * @mbggenerated
     */
    TradeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TradeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TradeOrder record);
}