package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.Trade;
import shit.ssm1.mybatis.BaseMapper;

import java.util.List;
import java.util.Map;

public interface TradeMapper extends BaseMapper<Trade, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated
     */
    Trade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Trade record);

    /**
     *
     * @param start
     * @param limit
     * @return
     */
    List<Trade> selectByPage(int start, int limit);
}