package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.UDisk;
import shit.ssm1.mybatis.BaseMapper;

public interface UDiskMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_u_disk
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_u_disk
     *
     * @mbggenerated
     */
    int insert(UDisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_u_disk
     *
     * @mbggenerated
     */
    int insertSelective(UDisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_u_disk
     *
     * @mbggenerated
     */
    UDisk selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_u_disk
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UDisk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table d_u_disk
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UDisk record);
}