package cn.wsn331.om.console.mapper;

import cn.wsn331.om.model.UserLogin;
import shit.ssm1.mybatis.BaseMapper;

public interface UserLoginMapper extends BaseMapper<UserLogin, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
    int insert(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
    int insertSelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
    UserLogin selectByPrimaryKey(Integer id);

    /**
     *
     * @param userId
     * @return
     */
    UserLogin selectByUserId(Integer userId);

    /**
     *
     * @param accessToken
     * @return
     */
    UserLogin selectByAccessToken(String accessToken);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserLogin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserLogin record);
}